name: actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [ 17.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: build production project
        run: yarn build:prod
      - name: linting typescript
        run: yarn eslint
      - name: linting css
        run: yarn stylelint
      - name: unit testing
#        if: always()
        run: yarn test:unit
#      - name: build storybook
#        run: yarn storybook:build
##        if: always()
#      - name: screenshot testing
#        run: yarn test:ui:ci
##        if: always()