name: actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [ 17.x ]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install modules
        run: yarn
      - name: build production project
        run: yarn build:prod
        if: always()
      - name: linting typescript
        if: always()
        run: yarn eslint
      - name: linting scss
        if: always()
        run: yarn stylelint
      - name: unit testing
        if: always()
        run: yarn test:unit
#      - name: build storybook
#        run: yarn storybook:build
#      - name: screenshot testing
#        run: yarn test:ui:ci
