name: actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
      node-version: [ 17.x ]
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: install modules
        run: yarn
      - name: build production project
        run: yarn build:prod
      - name: linting typescript
        run: yarn eslint
      - name: linting css
        run: yarn stylelint
      - name: unit testing
#        if: always()
        run: yarn test:unit
#      - name: build storybook
#        run: yarn storybook:build
##        if: always()
#      - name: screenshot testing
#        run: yarn test:ui:ci
##        if: always()